//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _in {
            get {
                object obj = ResourceManager.GetObject("in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _is {
            get {
                object obj = ResourceManager.GetObject("is", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 // Generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///// 2019-02-08: Updated to support shadowsocks-windows user rules.
        ///
        ///var proxy = &quot;__PROXY__&quot;;
        ///
        ///var userrules = __USERRULES__;
        ///var rules = __RULES__;
        ///
        ////*
        ///* This file is part of Adblock Plus &lt;http://adblockplus.org/&gt;,
        ///* Copyright (C) 2006-2014 Eyeo GmbH
        ///*
        ///* Adblock Plus is free software: you can redistribute it and/or modify
        ///* it under the terms of the GNU General Public License version 3 as
        ///* published by t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string abp_js {
            get {
                return ResourceManager.GetString("abp_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap at {
            get {
                object obj = ResourceManager.GetObject("at", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap au {
            get {
                object obj = ResourceManager.GetObject("au", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap user_set
        {
            get
            {
                object obj = ResourceManager.GetObject("user_set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap br {
            get {
                object obj = ResourceManager.GetObject("br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ca {
            get {
                object obj = ResourceManager.GetObject("ca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ch {
            get {
                object obj = ResourceManager.GetObject("ch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cl {
            get {
                object obj = ResourceManager.GetObject("cl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cn {
            get {
                object obj = ResourceManager.GetObject("cn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap connected {
            get {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cz {
            get {
                object obj = ResourceManager.GetObject("cz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap dk {
            get {
                object obj = ResourceManager.GetObject("dk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Earth {
            get {
                object obj = ResourceManager.GetObject("Earth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ee {
            get {
                object obj = ResourceManager.GetObject("ee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap fi {
            get {
                object obj = ResourceManager.GetObject("fi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap fr {
            get {
                object obj = ResourceManager.GetObject("fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gb {
            get {
                object obj = ResourceManager.GetObject("gb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gr {
            get {
                object obj = ResourceManager.GetObject("gr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hk {
            get {
                object obj = ResourceManager.GetObject("hk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hr {
            get {
                object obj = ResourceManager.GetObject("hr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap hu {
            get {
                object obj = ResourceManager.GetObject("hu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ie {
            get {
                object obj = ResourceManager.GetObject("ie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap in1 {
            get {
                object obj = ResourceManager.GetObject("in1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap it {
            get {
                object obj = ResourceManager.GetObject("it", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Japanese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///System Proxy=システムプロキシ
        ///Disable=無効
        ///PAC=PAC
        ///Global=全般
        ///Servers=サーバー
        ///Edit Servers...=サーバーの編集...
        ///Statistics Config...=統計情報の設定...
        ///Start on Boot=システムと同時に起動
        ///Forward Proxy...=フォワードプロキシの設定...
        ///Allow other Devices to connect=他のデバイスからの接続を許可する
        ///Local PAC=ローカル PAC
        ///Online PAC=オンライン PAC
        ///Edit Local PAC File...=ローカル PAC ファイルの編集...
        ///Update Local PAC from GFWList=GFWList からローカル PAC を更新
        ///Edit User Rule for GFWList...=ユーザールールの編集...
        ///Secure Local PA [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap jp {
            get {
                object obj = ResourceManager.GetObject("jp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap buy {
            get {
                object obj = ResourceManager.GetObject("buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap join_us
        {
            get
            {
                object obj = ResourceManager.GetObject("join_us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap vip
        {
            get
            {
                object obj = ResourceManager.GetObject("vip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap no_vip
        {
            get
            {
                object obj = ResourceManager.GetObject("no_vip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap share {
            get {
                object obj = ResourceManager.GetObject("share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Jupiter {
            get {
                object obj = ResourceManager.GetObject("Jupiter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap kr {
            get {
                object obj = ResourceManager.GetObject("kr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap lt {
            get {
                object obj = ResourceManager.GetObject("lt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap lv {
            get {
                object obj = ResourceManager.GetObject("lv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mars {
            get {
                object obj = ResourceManager.GetObject("Mars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mercury {
            get {
                object obj = ResourceManager.GetObject("Mercury", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Neptune {
            get {
                object obj = ResourceManager.GetObject("Neptune", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap nl {
            get {
                object obj = ResourceManager.GetObject("nl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap nz {
            get {
                object obj = ResourceManager.GetObject("nz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///toggle 0
        ///logfile ss_privoxy.log
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / __SOCKS_HOST__:__SOCKS_PORT__ .
        ///max-client-connections 2048
        ///hide-console
        /// 的本地化字符串。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] privoxy_exe {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 // Generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///// 2019-02-08: Updated to support shadowsocks-windows user rules.
        ///
        ///var proxy = &quot;__PROXY__&quot;;
        ///
        ///var userrules = [];
        ///var rules = [
        ///  &quot;|http://85.17.73.31/&quot;,
        ///  &quot;||agnesb.fr&quot;,
        ///  &quot;||akiba-web.com&quot;,
        ///  &quot;||altrec.com&quot;,
        ///  &quot;||angela-merkel.de&quot;,
        ///  &quot;||angola.org&quot;,
        ///  &quot;||apartmentratings.com&quot;,
        ///  &quot;||apartments.com&quot;,
        ///  &quot;||arena.taipei&quot;,
        ///  &quot;||asianspiss.com&quot;,
        ///  &quot;||assimp.org&quot;,
        ///  &quot;||athenaeizou.com&quot;,
        ///  &quot;||azubu.tv&quot;,
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string proxy_pac_txt {
            get {
                return ResourceManager.GetString("proxy_pac_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Saturn {
            get {
                object obj = ResourceManager.GetObject("Saturn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap se {
            get {
                object obj = ResourceManager.GetObject("se", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sg {
            get {
                object obj = ResourceManager.GetObject("sg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32Fill {
            get {
                object obj = ResourceManager.GetObject("ss32Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32In {
            get {
                object obj = ResourceManager.GetObject("ss32In", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32Out {
            get {
                object obj = ResourceManager.GetObject("ss32Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ss32Outline {
            get {
                object obj = ResourceManager.GetObject("ss32Outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ssw128 {
            get {
                object obj = ResourceManager.GetObject("ssw128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] sysproxy_exe {
            get {
                object obj = ResourceManager.GetObject("sysproxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] sysproxy64_exe {
            get {
                object obj = ResourceManager.GetObject("sysproxy64_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ua {
            get {
                object obj = ResourceManager.GetObject("ua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Uranus {
            get {
                object obj = ResourceManager.GetObject("Uranus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap us {
            get {
                object obj = ResourceManager.GetObject("us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// 的本地化字符串。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }

        internal static string line
        {
            get
            {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Venus {
            get {
                object obj = ResourceManager.GetObject("Venus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Simplified Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///System Proxy=系统代理
        ///Disable=禁用
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Servers=服务器
        ///Edit Servers...=编辑服务器...
        ///Statistics Config...=统计配置...
        ///Start on Boot=开机启动
        ///Forward Proxy...=正向代理设置...
        ///Allow other Devices to connect=允许其他设备连入
        ///Local PAC=使用本地 PAC
        ///Online PAC=使用在线 PAC
        ///Edit Local PAC File...=编辑本地 PAC 文件...
        ///Update Local PAC from GFWList=从 GFWList 更新本地 PAC
        ///Edit User Rule for GFWList...=编辑 GFWList 的用户规则...
        ///Secure Local PAC=保护本地 PAC
        ///Copy Lo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # translation for Traditional Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///System Proxy=系統代理
        ///Disable=禁用
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Servers=伺服器
        ///Edit Servers...=編輯伺服器...
        ///Statistics Config...=統計設定檔...
        ///Start on Boot=開機啟動
        ///Forward Proxy...=正向 Proxy 設定...
        ///Allow other Devices to connect=允許其他裝置連入
        ///Local PAC=使用本機 PAC
        ///Online PAC=使用線上 PAC
        ///Edit Local PAC File...=編輯本機 PAC 檔案...
        ///Update Local PAC from GFWList=從 GFWList 更新本機 PAC
        ///Edit User Rule for GFWList...=編輯 GFWList 的使用者規則...
        ///Secure Local PAC=安全本機 PAC
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_TW {
            get {
                return ResourceManager.GetString("zh_TW", resourceCulture);
            }
        }
    }
}
